// Export empty state SVG for convenience
export { default as APIEmptySVG } from './images/api_empty.svg'
export { default as AgentsEmptySVG } from './images/agents_empty.svg'
export { default as AssistantEmptySVG } from './images/assistant_empty.svg'
export { default as ChunksEmptySVG } from './images/chunks_empty.svg'
export { default as CredentialEmptySVG } from './images/credential_empty.svg'
export { default as DocStoreEmptySVG } from './images/doc_store_empty.svg'
export { default as DocStoreDetailsEmptySVG } from './images/doc_store_details_empty.svg'
export { default as LeadsEmptySVG } from './images/leads_empty.svg'
export { default as MessageEmptySVG } from './images/message_empty.svg'
export { default as PromptEmptySVG } from './images/prompt_empty.svg'
export { default as ToolsEmptySVG } from './images/tools_empty.svg'
export { default as UpsertHistoryEmptySVG } from './images/upsert_history_empty.svg'
export { default as VariablesEmptySVG } from './images/variables_empty.svg'
export { default as WorkflowEmptySVG } from './images/workflow_empty.svg'
