packages:
    - 'packages/*'
    - 'packages/*/base'

# Catalog - single source of truth for dependency versions
# Using conservative versions to minimize migration risk
catalog:
    # TypeScript toolchain - unified to 5.8.3 for consistent compilation across monorepo
    typescript: ^5.8.3
    
    # i18next ecosystem - downgraded to stable 23.x due to TypeScript 5.8 incompatibility
    # i18next 24.x uses 'const' type parameters syntax that causes parsing errors in TS 5.8
    # Version 23.16.8 is proven stable and widely used
    # react-i18next pinned to 15.5.3 (last version compatible with i18next 23.x without requiring 24.x)
    i18next: 23.16.8
    react-i18next: 15.5.3
    i18next-http-backend: ^2.7.0
    i18next-browser-languagedetector: ^8.0.2
    
    # React ecosystem - current stable
    react: ^18.3.1
    react-dom: ^18.3.1
    '@types/react': ^18.3.18
    '@types/react-dom': ^18.3.5
    
    # React Router - updated to latest for React 18 compatibility
    react-router: ^6.28.0
    react-router-dom: ^6.28.0
    
    # Build tools and bundlers
    tsdown: ^0.15.7
    vite: ^5.4.19
    '@vitejs/plugin-react': ^4.3.4
    vitest: ^2.1.8
    
    # MUI ecosystem - v6.x (latest stable)
    '@mui/material': ^6.5.0
    '@mui/icons-material': ^6.5.0
    '@emotion/react': ^11.14.0
    '@emotion/styled': ^11.14.1
    
    # MUI X - Advanced components (v7.x)
    '@mui/x-charts': ^7.22.2
    '@mui/x-data-grid': ^7.22.2
    '@mui/x-data-grid-pro': ^7.22.2
    '@mui/x-date-pickers': ^7.22.2
    '@mui/x-date-pickers-pro': ^7.22.2
    '@mui/x-tree-view': ^7.22.2
    
    # Testing utilities
    '@testing-library/react': ^14.3.1
    '@testing-library/jest-dom': ^6.8.0
    '@testing-library/user-event': ^14.6.1
    happy-dom: ^16.14.2
    
    # State Management & Data Fetching
    '@tanstack/react-query': ^5.62.13
    
    # UI Notifications
    notistack: ^3.0.1
    
    # TypeScript types
    '@types/node': ^20.12.12
    
    # Linting and formatting
    eslint: ^8.57.1
    
    # Utilities
    dayjs: ^1.11.18
    axios: ^1.7.9
    
    # Rate limiting - updated to latest stable
    express-rate-limit: ^8.2.0
    rate-limit-redis: ^4.2.3
    ioredis: ^5.8.2
    async-mutex: ^0.5.0
    
    # ORM - TypeORM for database operations
    typeorm: ^0.3.20
    
    # HTTP error handling
    http-errors: ^2.0.0
    '@types/http-errors': ^2.0.4
    
    # Form validation
    zod: ^3.25.76
    react-hook-form: ^7.54.2
    '@hookform/resolvers': ^3.9.1
    
    # React utilities
    html-react-parser: ^5.1.10
    use-debounce: ^10.0.6
    framer-motion: ^10.16.4
    react-perfect-scrollbar: ^1.5.8
    flowise-react-json-view: ^1.21.7
    react-markdown: ^8.0.6
    react-syntax-highlighter: ^15.5.0
    react-datepicker: ^4.21.0
    react-code-blocks: ^0.1.6
    react-color: ^2.19.3
    react-redux: ^8.0.5
    reactflow: ^11.5.6
    
    # Code editor (CodeMirror)
    '@uiw/react-codemirror': ^4.23.0
    '@uiw/codemirror-theme-vscode': ^4.23.0
    '@uiw/codemirror-theme-sublime': ^4.23.0
    '@codemirror/lang-javascript': ^6.2.4
    '@codemirror/lang-json': ^6.0.2
    '@codemirror/view': ^6.38.6
    '@codemirror/state': ^6.5.2
    '@codemirror/theme-one-dark': ^6.1.3
    codemirror: ^6.0.2