openapi: 3.1.0
info:
  title: Common Schemas
  version: 1.0.0

components:
  schemas:
    ApiError:
      type: object
      required:
        - error
        - message
        - statusCode
        - timestamp
        - path
      properties:
        error:
          type: string
          description: Error type identifier
          example: "ValidationError"
        message:
          type: string
          description: Human-readable error message
          example: "Invalid request body"
        statusCode:
          type: integer
          description: HTTP status code
          example: 400
        timestamp:
          type: string
          format: date-time
          description: Error occurrence timestamp (ISO 8601)
          example: "2025-11-02T10:00:00Z"
        path:
          type: string
          description: Request path that caused error
          example: "/api/v1/uniks"
        details:
          type: object
          description: Detailed validation errors (field-level)
          additionalProperties:
            type: string
          example:
            name: "Name must be between 1 and 255 characters"
            description: "Description cannot exceed 1000 characters"
    
    PaginationMeta:
      type: object
      required:
        - limit
        - offset
        - total
        - hasMore
      properties:
        limit:
          type: integer
          description: Applied pagination limit
          example: 100
          minimum: 1
          maximum: 1000
        offset:
          type: integer
          description: Applied pagination offset
          example: 0
          minimum: 0
        total:
          type: integer
          description: Total number of items matching query
          example: 256
          minimum: 0
        hasMore:
          type: boolean
          description: Whether more items are available
          example: true
