openapi: 3.1.0
info:
  title: Metaverse Schemas
  version: 1.0.0

components:
  schemas:
    Metaverse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
