openapi: 3.1.0
info:
  title: Profile Schemas
  version: 1.0.0

components:
  schemas:
    UserProfile:
      type: object
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
          format: email
        username:
          type: string
