export { createGlobalUsersRoutes, type GlobalUsersRoutesConfig } from './globalUsersRoutes'
export { createDashboardRoutes, type DashboardRoutesConfig } from './dashboardRoutes'
export { createInstancesRoutes, type InstancesRoutesConfig } from './instancesRoutes'
export { createLocalesRoutes, type LocalesRoutesConfig } from './localesRoutes'
export { createPublicLocalesRoutes, type PublicLocalesRoutesConfig } from './publicLocalesRoutes'
export { createAdminSettingsRoutes, type AdminSettingsRoutesConfig } from './adminSettingsRoutes'
