import { copyFileSync, existsSync, mkdirSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { LOCAL_NETWORK_ID, REPO_ROOT, runCommand } from './shared.mjs'

export const SUPPORTED_LOCAL_SUPABASE_TARGETS = new Set(['dev', 'e2e'])
export const SUPPORTED_LOCAL_SUPABASE_STACKS = new Set(['minimal', 'full'])

export const minimalExcludedServices = ['realtime', 'storage-api', 'imgproxy', 'edge-runtime', 'logflare', 'vector']

export const localSupabaseProfiles = {
    dev: {
        target: 'dev',
        projectId: 'upstream-universo-platformo-react',
        workdir: REPO_ROOT,
        configPath: path.join(REPO_ROOT, 'supabase/config.toml'),
        seedSourcePath: path.join(REPO_ROOT, 'supabase/seed.sql'),
        seedPath: path.join(REPO_ROOT, 'supabase/seed.sql'),
        networkId: LOCAL_NETWORK_ID,
        ports: {
            api: 54321,
            db: 54322,
            studio: 54323,
            inbucket: 54324,
            shadow: 54320,
            pooler: 54329
        }
    },
    e2e: {
        target: 'e2e',
        projectId: 'upstream-universo-platformo-react-e2e',
        workdir: path.join(REPO_ROOT, '.local/supabase-e2e'),
        configPath: path.join(REPO_ROOT, '.local/supabase-e2e/supabase/config.toml'),
        seedSourcePath: path.join(REPO_ROOT, 'supabase/seed.sql'),
        seedPath: path.join(REPO_ROOT, '.local/supabase-e2e/supabase/seed.sql'),
        networkId: LOCAL_NETWORK_ID,
        ports: {
            api: 55321,
            db: 55322,
            studio: 55323,
            inbucket: 55324,
            shadow: 55320,
            pooler: 55329
        }
    }
}

export function assertLocalSupabaseTarget(value) {
    if (SUPPORTED_LOCAL_SUPABASE_TARGETS.has(value)) return value
    throw new Error(`Unsupported local Supabase target "${value}". Use "dev" or "e2e".`)
}

export function assertLocalSupabaseStack(value) {
    if (SUPPORTED_LOCAL_SUPABASE_STACKS.has(value)) return value
    throw new Error(`Unsupported local Supabase stack "${value}". Use "minimal" or "full".`)
}

export function getLocalSupabaseProfile(target) {
    return localSupabaseProfiles[assertLocalSupabaseTarget(target)]
}

export function getExcludeArgs(stack) {
    const normalizedStack = assertLocalSupabaseStack(stack)
    if (normalizedStack === 'full') return []
    return minimalExcludedServices.flatMap((serviceName) => ['-x', serviceName])
}

export function getSupabaseWorkdirArgs(profile) {
    return ['--workdir', profile.workdir]
}

export function runSupabaseCli(profile, args) {
    return runCommand('supabase', [...getSupabaseWorkdirArgs(profile), ...args], { cwd: profile.workdir })
}

export function ensureLocalSupabaseProject(profile) {
    mkdirSync(path.dirname(profile.configPath), { recursive: true })

    if (profile.target === 'dev') {
        return { generated: false, configPath: profile.configPath, seedPath: profile.seedPath }
    }

    writeFileSync(profile.configPath, buildE2eSupabaseConfig(profile), { mode: 0o600 })

    if (existsSync(profile.seedSourcePath)) {
        copyFileSync(profile.seedSourcePath, profile.seedPath)
    } else {
        writeFileSync(profile.seedPath, '-- Empty local E2E Supabase seed.\n', { mode: 0o600 })
    }

    return { generated: true, configPath: profile.configPath, seedPath: profile.seedPath }
}

export function buildE2eSupabaseConfig(profile = localSupabaseProfiles.e2e) {
    const { ports } = profile

    return `# Generated by tools/local-supabase/profiles.mjs.
# Local E2E Supabase profile. Do not edit or commit generated files from .local/.
project_id = "${profile.projectId}"

[api]
enabled = true
port = ${ports.api}
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[api.tls]
enabled = false

[db]
port = ${ports.db}
shadow_port = ${ports.shadow}
health_timeout = "2m"
major_version = 17

[db.pooler]
enabled = false
port = ${ports.pooler}
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[db.migrations]
enabled = true
schema_paths = []

[db.seed]
enabled = true
sql_paths = ["./seed.sql"]

[db.network_restrictions]
enabled = false
allowed_cidrs = ["0.0.0.0/0"]
allowed_cidrs_v6 = ["::/0"]

[realtime]
enabled = true

[studio]
enabled = true
port = ${ports.studio}
api_url = "http://127.0.0.1:${ports.api}"
openai_api_key = "env(OPENAI_API_KEY)"

[inbucket]
enabled = true
port = ${ports.inbucket}

[storage]
enabled = true
file_size_limit = "50MiB"

[storage.s3_protocol]
enabled = true

[storage.analytics]
enabled = false
max_namespaces = 5
max_tables = 10
max_catalogs = 2

[storage.vector]
enabled = false
max_buckets = 10
max_indexes = 5

[auth]
enabled = true
site_url = "http://localhost:3100"
additional_redirect_urls = ["http://localhost:3100", "http://127.0.0.1:3100"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true
enable_anonymous_sign_ins = false
enable_manual_linking = false
minimum_password_length = 6
password_requirements = ""

[auth.rate_limit]
email_sent = 2
sms_sent = 30
anonymous_users = 30
token_refresh = 150
sign_in_sign_ups = 300
token_verifications = 300
web3 = 30

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false
secure_password_change = false
max_frequency = "1s"
otp_length = 6
otp_expiry = 3600

[auth.sms]
enable_signup = false
enable_confirmations = false
template = "Your code is {{ .Code }}"
max_frequency = "5s"
`
}
