export const PLAYCANVAS_EDITOR_UPSTREAM_REPOSITORY = 'https://github.com/playcanvas/editor'
export const PLAYCANVAS_EDITOR_UPSTREAM_TAG = 'v2.24.2'
export const PLAYCANVAS_EDITOR_UPSTREAM_COMMIT = '00360100b3b5747648eb3d7287421ef25491f5c7'
export const PLAYCANVAS_EDITOR_UPSTREAM_PACKAGE_VERSION = '2.24.2'
export const PLAYCANVAS_EDITOR_NODE_REQUIREMENT = '>=22.22.0'
export const PLAYCANVAS_EDITOR_ARTIFACT_OUTPUT_ROOT = 'dist/editor'
export const PLAYCANVAS_EDITOR_SMOKE_MODE = 'universo-full-upstream-ui'

export const createPlayCanvasEditorArtifactManifest = (builtAt) => ({
    upstreamRepository: PLAYCANVAS_EDITOR_UPSTREAM_REPOSITORY,
    upstreamTag: PLAYCANVAS_EDITOR_UPSTREAM_TAG,
    upstreamCommit: PLAYCANVAS_EDITOR_UPSTREAM_COMMIT,
    upstreamPackageVersion: PLAYCANVAS_EDITOR_UPSTREAM_PACKAGE_VERSION,
    nodeRequirement: PLAYCANVAS_EDITOR_NODE_REQUIREMENT,
    outputRoot: PLAYCANVAS_EDITOR_ARTIFACT_OUTPUT_ROOT,
    smokeMode: PLAYCANVAS_EDITOR_SMOKE_MODE,
    builtAt
})
