export { default as MetaverseList } from './pages/MetaverseList'
export { default as MetaverseDetail } from './pages/MetaverseDetail'
export { default as MetaverseBoard } from './pages/MetaverseBoard'
export { default as MetaverseAccess } from './pages/MetaverseAccess'
export { default as SectionDetail } from './pages/SectionDetail'
export { default as SectionsList } from './pages/SectionsList'
export { default as EntityDetail } from './pages/EntityDetail'
export { default as EntityList } from './pages/EntityList'

export { default as metaversesDashboard } from './menu-items/metaverseDashboard'
export { metaversesTranslations } from './i18n'
