openapi: 3.1.0
info:
  title: Workspaces Paths
  version: 1.0.0

paths:
  /uniks:
    get:
      tags:
        - Workspaces
      summary: List user workspaces
      description: |
        Returns paginated list of workspaces owned by authenticated user.
        
        **RLS Behavior**: Only user's own workspaces are returned.
        
        **Use Cases**:
        - Dashboard workspace list
        - Workspace selector in UI
        - API client workspace discovery
      operationId: listWorkspaces
      security:
        - BearerAuth: []
        - ApiKeyAuth: []
      parameters:
        - $ref: '../components/parameters/query-params.yml#/components/parameters/Limit'
        - $ref: '../components/parameters/query-params.yml#/components/parameters/Offset'
        - $ref: '../components/parameters/query-params.yml#/components/parameters/SortBy'
        - $ref: '../components/parameters/query-params.yml#/components/parameters/SortOrder'
      responses:
        '200':
          description: Workspace list successfully retrieved
          headers:
            X-Total-Count:
              $ref: '../components/responses/success.yml#/components/headers/X-Total-Count'
            X-Pagination-Has-More:
              $ref: '../components/responses/success.yml#/components/headers/X-Pagination-Has-More'
          content:
            application/json:
              schema:
                $ref: '../components/schemas/workspace.yml#/components/schemas/WorkspaceListResponse'
        '401':
          $ref: '../components/responses/errors.yml#/components/responses/Unauthorized'
        '429':
          $ref: '../components/responses/errors.yml#/components/responses/TooManyRequests'
        '500':
          $ref: '../components/responses/errors.yml#/components/responses/InternalError'
    
    post:
      tags:
        - Workspaces
      summary: Create new workspace
      description: |
        Creates a new workspace for authenticated user.
        
        **RLS Behavior**: Workspace is automatically owned by requesting user.
        
        **Rate Limiting**: 60 requests/minute (write operation)
      operationId: createWorkspace
      security:
        - BearerAuth: []
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../components/schemas/workspace.yml#/components/schemas/CreateWorkspace'
      responses:
        '201':
          description: Workspace created successfully
          content:
            application/json:
              schema:
                $ref: '../components/schemas/workspace.yml#/components/schemas/Workspace'
        '400':
          $ref: '../components/responses/errors.yml#/components/responses/BadRequest'
        '401':
          $ref: '../components/responses/errors.yml#/components/responses/Unauthorized'
        '429':
          $ref: '../components/responses/errors.yml#/components/responses/TooManyRequests'
        '500':
          $ref: '../components/responses/errors.yml#/components/responses/InternalError'

  /unik/{unikId}:
    parameters:
      - $ref: '../components/parameters/path-params.yml#/components/parameters/UnikId'
    
    get:
      tags:
        - Workspaces
      summary: Get workspace by ID
      description: |
        Returns workspace details by UUID.
        
        **RLS Behavior**: Returns 404 if workspace doesn't belong to user.
      operationId: getWorkspace
      security:
        - BearerAuth: []
        - ApiKeyAuth: []
      responses:
        '200':
          description: Workspace details
          content:
            application/json:
              schema:
                $ref: '../components/schemas/workspace.yml#/components/schemas/Workspace'
        '401':
          $ref: '../components/responses/errors.yml#/components/responses/Unauthorized'
        '404':
          $ref: '../components/responses/errors.yml#/components/responses/NotFound'
        '500':
          $ref: '../components/responses/errors.yml#/components/responses/InternalError'
    
    patch:
      tags:
        - Workspaces
      summary: Update workspace
      description: |
        Partially updates workspace properties.
        
        **RLS Behavior**: Update fails if workspace doesn't belong to user.
      operationId: updateWorkspace
      security:
        - BearerAuth: []
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../components/schemas/workspace.yml#/components/schemas/UpdateWorkspace'
      responses:
        '200':
          description: Workspace updated successfully
          content:
            application/json:
              schema:
                $ref: '../components/schemas/workspace.yml#/components/schemas/Workspace'
        '400':
          $ref: '../components/responses/errors.yml#/components/responses/BadRequest'
        '401':
          $ref: '../components/responses/errors.yml#/components/responses/Unauthorized'
        '404':
          $ref: '../components/responses/errors.yml#/components/responses/NotFound'
        '500':
          $ref: '../components/responses/errors.yml#/components/responses/InternalError'
    
    delete:
      tags:
        - Workspaces
      summary: Delete workspace
      description: |
        Permanently deletes workspace and all contained Spaces/Canvases.
        
        **⚠️ Warning**: This action is irreversible!
        
        **RLS Behavior**: Delete fails if workspace doesn't belong to user.
      operationId: deleteWorkspace
      security:
        - BearerAuth: []
      responses:
        '204':
          description: Workspace deleted successfully
        '401':
          $ref: '../components/responses/errors.yml#/components/responses/Unauthorized'
        '404':
          $ref: '../components/responses/errors.yml#/components/responses/NotFound'
        '500':
          $ref: '../components/responses/errors.yml#/components/responses/InternalError'
