import { qSchemaTable } from '@universo-react/database'
import type { DbExecutor, SqlQueryable } from '@universo-react/utils'
import { generateUuidV7 } from '@universo-react/utils'

export type EditorRealtimeBackupCollection = 'scenes' | 'assets' | 'settings' | 'user_data'

export interface EditorDocumentBackupRow {
    collection: EditorRealtimeBackupCollection
    documentId: string
    data: Record<string, unknown>
    version: number
}

export interface EditorDocumentBackupSetRow extends EditorDocumentBackupRow {
    openedAt: Date
}

export interface InsertEditorDocumentBackupSetInput {
    metahubId: string
    projectId: string
    openedAt: Date
    rows: readonly EditorDocumentBackupRow[]
}

const BACKUP_TABLE = qSchemaTable('metahubs', 'playcanvas_editor_document_backups')

/** Maximum number of newest backup sets retained per (metahub, project). */
export const EDITOR_DOCUMENT_BACKUP_MAX_SETS = 5

/**
 * Inserts a whole backup set as ONE transaction: the multi-row INSERT and the
 * keep-at-most-N pruning commit or roll back together, so a failure never leaves
 * partial backup rows behind.
 *
 * Returns the number of inserted rows. Ids are uuid v7 values generated by the caller
 * side of this store (generateUuidV7) so that `ORDER BY id` replays insertion order.
 */
export const insertEditorDocumentBackupSet = async (exec: DbExecutor, input: InsertEditorDocumentBackupSetInput): Promise<number> => {
    if (input.rows.length === 0) {
        return 0
    }

    const insert = async (tx: SqlQueryable): Promise<number> => {
        const inserted = await tx.query<{ id: string }>(
            `
                INSERT INTO ${BACKUP_TABLE}
                    (id, metahub_id, project_id, opened_at, collection, document_id, data, version)
                SELECT u.id, $2::uuid, $3::uuid, $4::timestamptz, u.collection, u.document_id, u.data, u.version
                FROM unnest(
                         $1::uuid[], $5::text[], $6::text[], $7::jsonb[], $8::integer[]
                     ) WITH ORDINALITY AS u(id, collection, document_id, data, version, ordinality)
                ORDER BY u.ordinality
                RETURNING id
            `,
            [
                input.rows.map(() => generateUuidV7()),
                input.metahubId,
                input.projectId,
                input.openedAt.toISOString(),
                input.rows.map((row) => row.collection),
                input.rows.map((row) => row.documentId),
                input.rows.map((row) => JSON.stringify(row.data)),
                input.rows.map((row) => row.version)
            ]
        )

        if (inserted.length !== input.rows.length) {
            throw new Error(
                `PlayCanvas Editor document backup set insert was incomplete: expected ${input.rows.length} rows, committed ${inserted.length}`
            )
        }

        await pruneEditorDocumentBackupSets(tx, {
            metahubId: input.metahubId,
            projectId: input.projectId,
            keepSets: EDITOR_DOCUMENT_BACKUP_MAX_SETS
        })

        return inserted.length
    }

    // Transaction executors returned by an outer lifecycle lock may expose only
    // the query surface in lightweight adapters. In that case the caller already
    // owns the transaction; executing directly preserves atomic composition and
    // avoids accidentally acquiring a second connection.
    return typeof exec.transaction === 'function' ? exec.transaction(insert) : insert(exec)
}

/**
 * Deletes every backup set outside the newest `keepSets` sets for the project.
 * A set is identified by its distinct `opened_at` timestamp; sets with fewer than
 * `keepSets` total sets delete nothing.
 */
export const pruneEditorDocumentBackupSets = async (
    exec: SqlQueryable,
    input: { metahubId: string; projectId: string; keepSets?: number }
): Promise<number> => {
    const keepSets = input.keepSets ?? EDITOR_DOCUMENT_BACKUP_MAX_SETS
    const deleted = await exec.query<{ id: string }>(
        `
            DELETE FROM ${BACKUP_TABLE} AS target
            WHERE target.metahub_id = $1::uuid
              AND target.project_id = $2::uuid
              AND target.opened_at NOT IN (
                  SELECT DISTINCT stale.opened_at
                  FROM ${BACKUP_TABLE} AS stale
                  WHERE stale.metahub_id = $1::uuid
                    AND stale.project_id = $2::uuid
                  ORDER BY stale.opened_at DESC
                  LIMIT $3
              )
            RETURNING target.id
        `,
        [input.metahubId, input.projectId, keepSets]
    )
    return deleted.length
}

/** True when a backup set already exists for the exact session marker (`opened_at`). */
export const latestEditorDocumentBackupSetExists = async (
    exec: SqlQueryable,
    input: { metahubId: string; projectId: string; openedAtMarker: Date }
): Promise<boolean> => {
    const rows = await exec.query<{ exists: boolean }>(
        `
            SELECT EXISTS(
                SELECT 1
                FROM ${BACKUP_TABLE}
                WHERE metahub_id = $1::uuid
                  AND project_id = $2::uuid
                  AND opened_at = $3::timestamptz
            ) AS "exists"
        `,
        [input.metahubId, input.projectId, input.openedAtMarker.toISOString()]
    )
    return rows[0]?.exists === true
}

/**
 * Loads every row of the newest backup set for the project in stored insertion order.
 * Returns an empty array when no backup set exists — callers must fail closed on it.
 */
export const listLatestEditorDocumentBackupRows = async (
    exec: SqlQueryable,
    input: { metahubId: string; projectId: string }
): Promise<EditorDocumentBackupSetRow[]> => {
    const rows = await exec.query<{
        collection: EditorRealtimeBackupCollection
        documentId: string
        data: Record<string, unknown>
        version: number
        openedAt: Date
    }>(
        `
            SELECT backup.collection AS "collection",
                   backup.document_id AS "documentId",
                   backup.data AS "data",
                   backup.version AS "version",
                   backup.opened_at AS "openedAt"
            FROM ${BACKUP_TABLE} AS backup
            WHERE backup.metahub_id = $1::uuid
              AND backup.project_id = $2::uuid
              AND backup.opened_at = (
                  SELECT MAX(latest.opened_at)
                  FROM ${BACKUP_TABLE} AS latest
                  WHERE latest.metahub_id = $1::uuid
                    AND latest.project_id = $2::uuid
              )
            ORDER BY backup.id
        `,
        [input.metahubId, input.projectId]
    )
    return rows.map((row) => ({
        collection: row.collection,
        documentId: row.documentId,
        data: row.data,
        version: row.version,
        openedAt: row.openedAt instanceof Date ? row.openedAt : new Date(row.openedAt)
    }))
}

/**
 * Deletes one exact backup set identified by its `opened_at` timestamp.
 * Fails closed when the set does not exist instead of reporting silent success.
 */
export const deleteEditorDocumentBackupSet = async (
    exec: DbExecutor,
    input: { metahubId: string; projectId: string; openedAt: Date }
): Promise<number> => {
    return exec.transaction(async (tx) => {
        const deleted = await tx.query<{ id: string }>(
            `
                DELETE FROM ${BACKUP_TABLE}
                WHERE metahub_id = $1::uuid
                  AND project_id = $2::uuid
                  AND opened_at = $3::timestamptz
                RETURNING id
            `,
            [input.metahubId, input.projectId, input.openedAt.toISOString()]
        )
        if (deleted.length === 0) {
            throw new Error('PlayCanvas Editor document backup set was not found for deletion')
        }
        return deleted.length
    })
}
